version: "3.3"
services:
    db:
        image: "mysql:latest"
        container_name: mydockerbox-mysql
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
        restart: always
        volumes:
            - data-volumes:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        depends_on:
            - db
        ports:
            - 8080:8080
networks:
    my-network:
volumes:
    data-volumes:
